### ISSUE TITLE
Glitchy SA-X Death

### ISSUE THREAD

**Issue by Miepee** [milesthenerd/AM2R-Multitroid#31]
**Describe the bug**
SA-X death does not work correctly: in the vast majority of situations, the SA-X does not become a Core X as they should, and instead immediately see a game over screen to respawn from, upon which they are in a glitched state that makes them invisible to Fusion players. Some players also experience extreme lag while in this glitched state.

**To Reproduce**
Let an sa-x player die.

**Expected behavior**
The SA-X should transform into a core-x

**Platform (please complete the following information):**
 - OS: Win10

**Game Version:**
1.4.2

**Comment by milesthenerd** [comment]
Fixed in commit 4bff19e20dce18400fb5023ba4f2b1dd78d008df
